apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlphttp/dynatrace:
        endpoint: "https://klo77120.live.dynatrace.com/api/v2/otlp"
        headers:
          Authorization: "Api-Token dt0c01.AA2BCRCMKPXHKLWJ3DARZRBK.M3NCEEEHJUBKHDESCNWXKQ2FO4DEEQUUX5C6R5PCFX3S6DWOUUB7RDDPNPKIRFBE"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlphttp/dynatrace]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.79.0
          command:
            - "/otelcol-contrib"
            - "--config=/etc/otel-config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-config.yaml
              subPath: otel-config.yaml
          ports:
            - containerPort: 4317
            - containerPort: 4318
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: default
spec:
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
  selector:
    app: otel-collector
