apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: default
  annotations:
    instrumentation.opentelemetry.io/inject-python: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: python-app
          image: ghcr.io/sonoflope/python-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: 'true'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-shop-demo-otelcol:4318
            - name: OTEL_SERVICE_NAME
              value: python-app
            - name: OTEL_COLLECTOR_NAME
              value: 'otel-shop-demo-otelcol'
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=python-app,service.namespace=default,service.version=latest
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_LOG_LEVEL
              value: "debug"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_TRACES_EXPORTER
              value: console
            - name: OTEL_METRICS_EXPORTER
              value: console
            - name: OTEL_LOGS_EXPORTER
              value: console
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: default
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: contour
  tls:
  - hosts:
    - python.gcp.sonoflope.ca
    secretName: python-gcp-sonoflope-ca-tls
  rules:
  - host: python.gcp.sonoflope.ca
    http:
      paths: 
        - path: /
          pathType: Prefix
          backend:
            service:
              name: python-app
              port:
                number: 8080
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-app-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: "http://otel-shop-demo-otelcol:4318"
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  python:
    env:
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-shop-demo-otelcol:4318
      - name: OTEL_SERVICE_NAME
        value: python-app