branch: main
directory:
  - terraform
  - gke/apps
output: cli
soft-fail: false
quiet: true
check: # Policy index https://www.checkov.io/5.Policy%20Index/all.html
  # GCP checks
  - CKV_GCP_10
  - CKV_GCP_9
  - CKV_GCP_23

  # Kubernetes checks
  - CKV_K8S_27
  - CKV_K8S_29
  - CKV_K8S_30
  - CKV_K8S_32
  - CKV_K8S_35
  - CKV_K8S_36
  - CKV_K8S_37
  - CKV_K8S_39
  - CKV_K8S_41

  # Docker checks
  - CKV_DOCKER_2
  - CKV_DOCKER_3
  - CKV_DOCKER_6

skip-check:
  - CKV_GCP_1
