apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectcontour
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  source:
    repoURL: 'https://github.com/SonOfLope/tf-gke-cluster.git'
    path: gke/system/contour/base
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true