apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: otel-shop-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: opentelemetry-helm
      helm:
        releaseName: otel-shop-demo
        valueFiles:
        - $values/gke/apps/otel-demo/helm/values.yaml
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.30.5
    - repoURL: 'https://github.com/SonOfLope/tf-gke-cluster.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/SonOfLope/tf-gke-cluster.git'
      path: gke/apps/otel-demo/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true