name: SCA Checkov Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Checkov
        run: pip install checkov

      # - name: Run Checkov Scan
      #   run: checkov --config-file .checkov.yml

  terraform-cloud:
    needs: [checkov-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      - name: Trigger terraform run
        run: terraform cloud run-trigger --workspace=tf-gke-cluster