apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dynatrace
  namespace: argocd
spec:
  destination:
    namespace: dynatrace
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: dynatrace-operator
      helm:
        releaseName: dynatrace
      repoURL: oci://public.ecr.aws/dynatrace/dynatrace-operator
      targetRevision: 1.4.0
    - repoURL: 'https://github.com/SonOfLope/tf-gke-cluster.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/SonOfLope/tf-gke-cluster.git'
      path: gke/system/dynatrace/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true